backend:
  name: github
  repo: Josue1204/SpaErika # CAMBIA ESTO
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "configuracion"
    label: "Configuración Web"
    files:
      - file: "data/config.json"
        label: "Contenido General"
        name: "general"
        fields:
          - {label: "Nombre del Spa", name: "titulo", widget: "string"}
          - {label: "Texto Sobre Mí", name: "sobre_mi", widget: "text"}
          - {label: "Precio Básico", name: "precio_basico", widget: "number"}
          - {label: "Precio Premium", name: "precio_premium", widget: "number"}
          - {label: "IDs de Videos (separados por coma)", name: "videos", widget: "list"}
