backend:
  name: git-gateway
  repo: josue1204/SpaErika  # Debe ser exactamente tu usuario/repositorio
  branch: main # Verifica si tu rama se llama main o master
  base_url: https://josue1204.github.io/SpaErika/

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "configuracion"
    label: "Panel de Control Erika"
    files:
      - file: "data/config.json"
        label: "Editar Contenido de la Web"
        name: "general"
        fields:
          - {label: "🏨 Nombre de la Web", name: "titulo", widget: "string", hint: "El nombre que aparece arriba en el menú."}
          - {label: "👤 Biografía (Sobre Mí)", name: "sobre_mi", widget: "text", hint: "Escribe una descripción breve sobre ti."}
          - {label: "💵 Precio Masaje Básico", name: "precio_basico", widget: "number", value_type: "int"}
          - {label: "💎 Precio Matriz / Premium", name: "precio_premium", widget: "number", value_type: "int"}
          - label: "🎥 Galería de Videos de YouTube"
            name: "videos"
            widget: "list"
            summary: "Video: {{fields.video}}"
            add_to_top: true
            field: {label: "Pega el link de YouTube aquí", name: "video", widget: "string"}
